inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Bundler/OrderedGems:
  Severity: warning
  AllowForAlignment: true
  sExclude:
    - 'Gemfile'

Layout/AlignHash:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'app/mailers/notice_mailer.rb'
    - 'config/environments/development.rb'
    - 'config/initializers/simple_form.rb'

Layout/CommentIndentation:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'app/controllers/comments_controller.rb'

Layout/EmptyLineAfterMagicComment:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'config/initializers/simple_form.rb'

Layout/EmptyLineBetweenDefs:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'app/controllers/articles/comments_controller.rb'
    - 'app/controllers/articles_controller.rb'
    - 'app/controllers/comments_controller.rb'

Layout/EmptyLines:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'Gemfile'
    - 'app/controllers/homes_controller.rb'
    - 'bin/setup'
    - 'db/migrate/20181124175529_create_devise_to_users.rb'
    - 'spec/features/users_spec.rb'

Layout/EmptyLinesAroundAccessModifier:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/articles/comments_controller.rb'
    - 'app/controllers/articles_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/users_controller.rb'

Layout/EmptyLinesAroundBlockBody:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundClassBody:
  Severity: warning
  AllowForAlignment: true

Layout/IndentationConsistency:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/articles/comments_controller.rb'
    - 'app/controllers/articles_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/users_controller.rb'

Layout/LeadingCommentSpace:
  Severity: warning
  AllowForAlignment: true

Layout/IndentationWidth:
  Severity: warning
  AllowForAlignment: true
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/articles/comments_controller.rb'
    - 'app/controllers/articles_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/users_controller.rb'

Layout/SpaceBeforeBlockBraces:
  Severity: warning
  AllowForAlignment: true

Layout/SpaceInsideArrayLiteralBrackets:
  Severity: warning
  AllowForAlignment: true

Layout/TrailingBlankLines:
  Severity: warning
  AllowForAlignment: true

Layout/TrailingWhitespace:
  Exclude:
    - 'config/initializers/devise.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'app/models/ability.rb'

Metrics/AbcSize:
  Max: 26

# Offense count: 3
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 46

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 27

# Offense count: 2
# Configuration parameters: EnforcedStyle.
# SupportedStyles: slashes, arguments
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/rails_helper.rb'

# Offense count: 3
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/article.rb'
    - 'app/models/user.rb'

# Offense count: 1
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/20181124175113_drop_table_users.rb'

# Offense count: 5
# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Exclude:
    - 'app/controllers/comments_controller.rb'
    - 'spec/features/users_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'spec/features/users_spec.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/articles/comments_controller.rb'
    - 'app/controllers/user/confirmations_controller.rb'
    - 'app/controllers/user/omniauth_callbacks_controller.rb'
    - 'app/controllers/user/passwords_controller.rb'
    - 'app/controllers/user/registrations_controller.rb'
    - 'app/controllers/user/sessions_controller.rb'
    - 'app/controllers/user/unlocks_controller.rb'
    - 'test/test_helper.rb'

# Offense count: 22
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/articles/comments_controller.rb'
    - 'app/controllers/articles_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/homes_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/mailers/notice_mailer.rb'
    - 'app/models/ability.rb'
    - 'app/models/application_record.rb'
    - 'app/models/article.rb'
    - 'app/models/comment.rb'
    - 'app/models/user.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'config/application.rb'
    - 'db/migrate/20181109111344_create_users.rb'
    - 'db/migrate/20181124175113_drop_table_users.rb'
    - 'db/migrate/20181124175529_create_devise_to_users.rb'
    - 'db/migrate/20181204040735_create_articles.rb'
    - 'db/migrate/20181214165209_create_comments.rb'
    - 'db/migrate/20181218033053_add_status_to_comment.rb'

# Offense count: 7
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'spec/rails_helper.rb'
    - 'test/test_helper.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'config/environments/development.rb'

# Offense count: 2
Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/comments_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'spec/models/article_spec.rb'

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

# Offense count: 1
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/views/homes/show.csv.ruby'
    - 'config/spring.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Offense count: 87
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'app/mailers/notice_mailer.rb'
    - 'app/models/article.rb'
    - 'bin/spring'
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'db/migrate/20181124175529_create_devise_to_users.rb'
    - 'db/migrate/20181218033053_add_status_to_comment.rb'
    - 'db/schema.rb'
    - 'spec/factories/users.rb'
    - 'spec/features/users_spec.rb'
    - 'spec/models/article_spec.rb'
    - 'spec/rails_helper.rb'
    - 'test/application_system_test_case.rb'
    - 'test/mailers/notice_mailer_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'bin/yarn'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 5

# Offense count: 77
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154